sudo: required

services:
  - docker

before_install:
  - docker build -t mahakagarwal248/client -f Dockerfile.dev .

script:
  - docker run -e CI=true mahakagarwal248/client npm test -- --coverage

after_success:
  #decrypt service account
  - openssl enc -aes256 -d -in serviceAccount.json.enc -out serviceAccount.json -k $SERVICE_KEY
  #install GCP sdk , delete old versions
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi

  - source /home/travis/google-cloud-sdk/path.bash.inc
  # get google authorization
  - gcloud auth activate-service-account --key-file serviceAccount.json
  #set up project
  - gcloud config set project gopalashringar
  - gcloud config set compute/zone asia-south1-a
  #build production grade dockerfile
  - docker build -t mahakagarwal248/client .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push mahakagarwal248/client
  - bash ./deploy.sh
